commcare_export/commcare_minilinq.py, commcare_export/excel_query.py, commcare_export/writers.py, tests/test_commcare_minilinq.py, tests/test_excel_query.py
All resources support the same filtering mechanism via URL parameters.
This will allow specifying other filters for the form endpoint without relying on the `_search` backdoor.
=> standardize filters

.travis.yml, commcare_export/cli.py, commcare_export/env.py, commcare_export/minilinq.py, commcare_export/misc.py, commcare_export/writers.py, setup.py, tests/test_minilinq.py, tests/test_writers.py
@millerdev 
This allows you to map value to dates, timestamps, booleans.
Previously those would all be saved to SQL as strings.
Added docs here: https://confluence.dimagi.com/display/commcarepublic/CommCare+Data+Export+Tool#CommCareDataExportTool-E.TypeSupport
=> Add type support

commcare_export/cli.py, commcare_export/commcare_hq_client.py, commcare_export/commcare_minilinq.py, tests/test_commcare_hq_client.py, tests/test_commcare_minilinq.py
To get around the issue of deep paging where the deeper the page the longer the query takes.
=> paginate by date for forms and cases

commcare_export/commcare_hq_client.py, commcare_export/commcare_minilinq.py
The current code naively sets the checkpoint to the
datetime that the batch was downloaded as opposed to the
'since date' in the last item of the batch.
This means that any interruptions in the export
would not correctly restart from where they left off
but would instead only export data that was updated
since the last run.
=> set batch checkpoint date to correct date

README.md, commcare_export/checkpoint.py, commcare_export/cli.py, commcare_export/utils.py, commcare_export/utils_cli.py, commcare_export/writers.py, migrations/versions/d82e1d06a82c_add_key_column.py, setup.py, tests/conftest.py, tests/test_checkpointmanager.py, tests/test_cli.py
This addresses https://github.com/dimagi/commcare-export/issues/94 by adding a new command line parameter `checkpoint-key`.
When that param is supplied the tool will use it as the search key for finding previous checkpoints instead of the query file MD5. Triggering a full rebuild can be done either by changing the value of the key parameter or using the `--start-over` param.
This PR also includes a tool to assist in going from non-keyed mode to keyed mode without losing history.
Easiest reviewed per commit.
=> checkpoint key

README.md, commcare_export/cli.py, commcare_export/commcare_hq_client.py, commcare_export/excel_query.py, commcare_export/writers.py, setup.py, tests/test_writers.py
this makes it substantially easier to run commcare hq and commcare-export in the same python environment (and generally seems good to upgrade libraries).
@snopoke I tested basic query file reading and writing to an `.xlsx` file. do you know what else I should be testing or if there are other gotchas you might expect with this change?
**EDIT: It looks like at least one change is that Excel 2007+ files are required to have a valid `'.xlsx'` extension even if they were previously valid files with a different name... Not sure if that's a problem.**
=> openpyexcel upgrade

commcare_export/checkpoint.py, commcare_export/commcare_hq_client.py
@snopoke I'm not 100% sure about this but I think this is a potentially big oversight in the tool that could be causing lost/missing data.
What we observed when doing the local ingestions on ICDS was that the final checkpoint got set to today, even though we only ever saw data through September 2018 (or whenever).
By using the system's local time to set the checkpoint on the last request you are essentially saying that the server APIs can never get behind. This is obviously heavily exacerbated in the scenario we are using, but we know that ES gets behind all the time which I think could create gaps in the exports in steady state if people's exports are relying on local system time for the last checkpoint.
Note: this means the last checkpoint will not ever be set (assuming the tool …
=> don't set checkpoint based on the current time

commcare_export/env.py, tests/test_minilinq.py
https://dimagi-dev.atlassian.net/browse/HI-707
This will allow creating SHA1 hashes of any column values. The specific use case is when exporting repeat groups the 'ID' field can be a long string which is too long for the column to accommodate:
```
'319e866e-c20a-413a-b1d9-fa2471f19cdc.form.data_fisher.319e866e-c20a-413a-b1d9-fa2471f19cdc.form.data_fisher.[0].details_capture.319e866e-c20a-413a-b1d9-fa2471f19cdc.form.data_fisher.319e866e-c20a-413a-b1d9-fa2471f19cdc.form.data_fisher.[0].details_capture.[0]'
```
Adding the `sha1` to the query file will convert the long value to a hash while still maintaining the uniqueness of the key.
=> add sha1 filter

commcare_export/commcare_hq_client.py
Allows CommCare Export to back off when it receives a 429 response ("Too Many Requests") from CommCare HQ.
=> Back off on 429 response

commcare_export/cli.py
I don't think this is ever used and if the user forgets to pass the `query` arg then the tool hangs forever waiting for stdin. You can still use a json query by having it in a file: `--query=query.json`
=> drop option to read json query from stdin

README.md, tests/conftest.py
I added one conditional to conftest.py because rollback caused an error with MSSQL in my environment, and I documented the way I found to install MSSQL on a Mac.
These changes are not too important by themselves, but I wanted to make sure I can run tests and go through the process of creating a pull request at least once before making more substantial changes.
=> Changes to support Mac OS

README.md
Here is a change to add documentation about the two new options.
Since I can't edit the [CommCare Wiki](https://confluence.dimagi.com/display/commcarepublic/CommCare+Data+Export+Tool#CommCareDataExportTool-Optionalcommcare-exportflags), I tried to create my own Confluence page with the [additional documentation](https://solleks.atlassian.net/wiki/spaces/CD/pages/32953/Data+Export+Tool+edits). Maybe you'll be able to cut & paste it into yours.
=> Document --users and --locations options

commcare_export/writers.py
This changes the default oracle text column to an NVARCHAR2(4000)
=> oracle column

commcare_export/cli.py
This makes it easier to programatically access these (which is used by commcare sync)
=> use stderr instead of stdout for error messages

commcare_export/cli.py
commcare-sync is incorrectly reporting auth failures as "success" which is confusing.
=> properly return failure exit status in event of auth fail or interruption

README.md, commcare_export/builtin_queries.py, commcare_export/cli.py, commcare_export/excel_query.py, commcare_export/location_info_provider.py, tests/test_cli.py, tests/test_excel_query.py
Here is a simplified version of the change to add organizational data to the export tool. It avoids creating views in a database to reduce brittleness in the face of changes.
The features of the simplified version are:
- add commcare_userid to Excel query specs when --with-organization is used.
- add one column to the commcare_locations table for each organization level and populate it with the location_id of a location's ancestor at that level.
- document the typical pattern for joining user, location and form data together in SQL.
=> Simplified --with-organization change

commcare_export/cli.py, tests/test_cli.py
when there is more than "one batch" of cases with the same timestamp, the importer will loop forever.
The case importer [defaults to submitting cases in chunks of 100](https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/case_importer/do_import.py#L35) which means that if you use the default setting and have done a case import of > 100 cases you can easily run into this.
=> increase the default batch size

commcare_export/location_info_provider.py
Try to fix a DET bug reported via Slack:
https://app.slack.com/client/T02QG622C/CGL7960TV
The line number was missing, but most likely, a previously unseen location resource URI was used as a key in the location_data table. It was probably the parent location of some location that was in the table. That contradicts my assumption that all locations and their parents would be provided by the api_client iterating over the 'location' endpoint.
This fix just changes fatal KeyErrors into warnings, so customers can keep using the --locations feature.
=> Avoid fatal errors for unknown locations or types

commcare_export/writers.py
When moving to an [explicit table object from dict](https://github.com/dimagi/commcare-export/commit/dc256537084e57951075eb325871fd00900976f1), markdown support got broken. 
Not a big deal, but it's the first thing we tell people to use in the docs, so probably good to get pushed out sooner rather than later.
=> Fix markdown output

commcare_export/cli.py, commcare_export/commcare_hq_client.py, tests/test_commcare_hq_client.py
Here is one short-term solution to the problem of batches with all the same timestamp - stop and suggest that the user increase the batch size.
Related doc: https://docs.google.com/document/d/1YnS9mN2gxG-OBREoxLNgpWwIJJgIFW-4NU2QznKG0XM/edit?ts=5ede8253#
I asked some questions in email about the alternative solution of checking for repeated results.
=> Raise exception on repeated requests with no progress

commcare_export/commcare_hq_client.py
https://dimagi-dev.atlassian.net/browse/SAAS-11041
Introduced in https://github.com/dimagi/commcare-export/pull/149/
Because we are modifying the `params` object in place the [equality check](https://github.com/dimagi/commcare-export/pull/149/files#diff-e9b8e26e329e2f147322d44dd1799109R133) was always returning `True`, causing the request to fail after 10 tries.
=> don't modify params in place

README.md, commcare_export/env.py, tests/test_env.py, tests/test_minilinq.py
This allows UUIDs to be recognized by databases with a UUID data type, like PostgreSQL and SQL Server.
cc @czue
=> hex2uuid formats UUIDs

README.md, commcare_export/env.py, tests/test_map_format.py, tests/test_minilinq.py
Quick addition based off conversation on slack. It's currently possible to get this with by using the following Map expression `template(https://www.commcarehq.org/a/{}/reports/form_data/{}/, $.domain, $.id)`.
The CommCare Excel export allow adding a `form_link` column which exports the URL to the form. I made these `X_url` to match the `template_url` function but open to changing it `X_link`.
=> add form_url & case_url functions

commcare_export/writers.py, tests/test_writers.py
We've had issues where columns are getting created in mssql that can't be indexed because the length is not getting set correctly.
https://dimagi-dev.atlassian.net/browse/SC-988?focusedCommentId=100916&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-100916
This change sets a max length, but then overrides this if any data is bigger than the 900 byte maximum. These resized columns will no longer be able to be indexed, but having indices on large columns seems funny anyway.
=> Set mssql nvarchar columns to fixed length to allow indexing

commcare_export/minilinq.py, commcare_export/specs.py, commcare_export/writers.py
This change https://github.com/dimagi/commcare-export/commit/842ad486cd2ee633fc5b8baeb14f91d1b1f565e6 which came from this comment https://github.com/dimagi/commcare-export/pull/142#discussion_r431918276 results in placing ALL the export data in memory before writing any of it to the output.
To fix that I've remove the code that eagerly evaluates the generator and also remove the rows from the equality check and JSON output of the TableSpec class (they definitely don't belong in either).
This should also fix https://dimagi-dev.atlassian.net/browse/SAAS-11588
Thanks to @bderenzi for noticing the weirdness and working through the debugging with me.
=> don't evaluate the generator

commcare_export/data_types.py, commcare_export/writers.py, tests/test_writers.py
This adds support for Postgres JSON column types. This is particularly useful if you want to use the DET to generate a "data lake" by exporting the entire contents of e.g. the "form" property.
I was shocked how easy this was. Only one little quirk to chase down with type compatibility.
=> support JSON columns in Postgres

commcare_export/cli.py, commcare_export/writers.py, tests/conftest.py, tests/test_writers.py
The test passes locally with my changes, but for some reason I'm inclined to feel that this PR still needs a migration to alter the existing MySQL columns' CHARACTER SET and COLLATION settings to `utf8mb4` and `utf8mb4_unicode_ci` respectively...or is my hunch wrong?
See [ticket](https://dimagi-dev.atlassian.net/browse/SC-1315)
=> Change mysql collation and charset from utf8 -> utf8mb4

commcare_export/commcare_hq_client.py, tests/test_commcare_hq_client.py
The new `messaging-events` API does not include a `meta.total_count` field.
First commit is the fix - the rest are a minor refactor.
=> fix key error if `meta.total_count` is not present

commcare_export/cli.py, commcare_export/env.py, commcare_export/excel_query.py, commcare_export/jsonpath_utils.py, tests/test_excel_query.py, tests/test_minilinq.py
The focus of the changes here is to allow exporting data from the messaging event API even when there are no messages. Each event may have multiple messages so in order to get one row per message we need an expression like this:
```
messaging-event.messages.[*]
```
However if there are no messages, as is the case when the event errors, we still want to export one row for the event. To accomplish this a new command line option is added to the CLI:
```
--export-root-if-no-subdocument
Use this when you are exporting a nested document e.g. form.form..case, messaging-event.messages.[*]
And you want to have a record exported even if the nested document does not exist or is empty.
```
When this option is used in conjunction with a Data Source query like those given in the examples, the minilnq …
=> Ability to emit the root document if the desired sub-document does not exist

commcare_export/env.py, commcare_export/excel_query.py, commcare_export/jsonpath_utils.py, commcare_export/misc.py, setup.py, tests/test_commcare_minilinq.py, tests/test_minilinq.py
PR on top of https://github.com/dimagi/commcare-export/pull/189
jsonpath-ng is a fork of jsonpath-rw with some additional features and a number of bugfixes. Since jsonpath-rw is not currently maintained it makes sense to move to jsonpath-ng. jsonpath-ng is also used in HQ.
=> switch to jsonpath-ng

commcare_export/env.py, tests/test_minilinq.py
This is useful for the messaging API:
Data Source: `messaging-event`
Source field: `messages[*].phone_number`
Value without unique: `+16199555086,+16199555086,+16199555086,+16199555086`
Value with unique: `+16199555086`
=> add unique function for removing duplicate values when exporting lists

setup.py
I assume there's some step after this about cutting a new release of the DET, but not sure how to do that.
=> FIX: Alembic 1.7.x is breaking migrations

README.md
New users installing commcare-export end up with an unsupported alembic version.
=> Update readme with pinned version of alembic

commcare_export/data_types.py
As I was testing out the DET configuration with `--strict-types`, type `text` could not be recognised. Turns out `DATA_TYPES_TO_SQLALCHEMY_TYPES` did not have a key-value pair for `DATA_TYPE_TEXT`.
=> Add DATA_TYPE_TEXT to DATA_TYPES_TO_SQLALCHEMY_TYPES

.travis.yml, commcare_export/writers.py, setup.py
This change allows us to support the current stable version of Alembic, by fixing an import error.
I have checked all other Alembic imports, and they all check out OK. Local testing succeeded.
=> Fix import for Alembic>=1.7

.travis.yml, commcare_export/env.py, commcare_export/minilinq.py, commcare_export/utils.py, mypy.ini, mypy_typed_modules.txt
Controversial, I know. But `env.py` and `minilinq.py` have had type hints since 2013. They were just in docstrings. This change converts what was written in the docstrings to actual type hints, and adds automated checking with Travis.
=> Move types from docstrings into type hints

README.md, setup.py
Small. No code changes, just documentation and a string:
There can be only one spelling.
=> "CommCare HQ"

commcare_export/writers.py, tests/test_checkpointmanager.py, tests/test_cli.py, tests/utils.py
Context: [SC-2022](https://dimagi-dev.atlassian.net/browse/SC-2022)
This change improves performance by avoiding [reflecting all the tables](https://docs.sqlalchemy.org/en/14/core/reflection.html#reflecting-all-tables-at-once) in a database.
This change has been tested with:
Easier to :blowfish: review :tropical_fish: by :fish: commit.
=> We don't need to reflect all the tables

commcare_export/excel_query.py, tests/test_excel_query.py
Context: [SC-2201](https://dimagi-dev.atlassian.net/browse/SC-2201)
PR for Case List API support: https://github.com/dimagi/commcare-hq/pull/32566
If a filter name is repeated with multiple filter values, commcare-export will pass both values to the API, not just the last one.
Once the PR linked above is merged, the Case List API will return cases that match any of the values. (In other words, an "OR" filter will be applied to multiple values of the same filter name.)
Tested locally.
fyi @joxl / SAAS
=> Preserve values of duplicate filter names

.github/workflows/test.yml, commcare_export/commcare_minilinq.py
[Ticket](https://dimagi-dev.atlassian.net/browse/SC-2911)
Background:
This work adds support to the DET for exporting data sources from CommCareHQ using the `api_get_ucr_data` API endpoint.
Due to the generic nature of the DET, not much work was needed to make the UCR exports compatible. 
One thing to note:
The datasources on HQ is stored in a custom table. This table does not have an `id` column and uses the `doc_id` column as the primary key. When HQ gives the datasource data it adds an `id` column (in addition to the `doc_id` column) which contains the same value as the `doc_id` column, but this new `id` column is the primary key in the DET database. If this is a problem I can change that, but that will require some additional changes to the DET.
=> Add UCR support

commcare_export/commcare_minilinq.py, tests/test_paginator.py
This PR fixes two issues:
1. the default page size was set to 1k which is the non-datesource default. This is now set to the DEFAULT_UCR_PAGE_SIZE, which is 10k.
2. the page_size (or batch-size) wasn't being passed as a query parameter
=> Fix for datasource's paginator page_size

README.md
I tried to use the example given in the Readme to get all the cases for a domain but failed to do so because the current example does not work and the internal APIs of commcare-export have changed.
After getting help from @kaapstorm I was able to write up a snippet that fetches all the cases, the PR updates that example.
=> Update readme with working example of using Commcare API

setup.py
Ticket: https://dimagi-dev.atlassian.net/browse/SAAS-15164
Client is having `AttributeError: module 'backoff' has no attribute 'runtime'`. According to [their changelog](https://github.com/litl/backoff/blob/master/CHANGELOG.md), they just `Add backoff.runtime` in version 2.0.0
=> specify backoff version

.github/workflows/test.yml, commcare_export/commcare_hq_client.py, tests/test_commcare_hq_client.py
https://dimagi.atlassian.net/browse/SC-3354
`raise for status` raises an exception in case of authentication failures which leads to a full stacktrace shown.
Seems reasonable to limit showing the full stacktrace only for verbose mode.
=> Show detailed exception only when needed

commcare_export/env.py
Context: [SC-3355](https://dimagi.atlassian.net/browse/SC-3355)
Sample output:
```
2024-02-13 23:57:04,479 commcare_export.writers WARNING  Adding column 'impact_case.column_112 VARCHAR(32) COLLATE "utf8mb4_unicode_ci"'
2024-02-13 23:57:04,509 root         ERROR    Row size too large. You may be trying to export too many columns. A maximum of 200 columns is suggested.
```
Full stacktrace when called with `--verbose`:
```
2024-02-13 23:31:52,206 commcare_export.writers WARNING  Adding column 'impact_case.column_111 VARCHAR(32) COLLATE "utf8mb4_unicode_ci"'
2024-02-13 23:31:52,244 commcare_export.writers WARNING  Adding column 'impact_case.column_112 VARCHAR(32) COLLATE "utf8mb4_unicode_ci"'
Traceback (most recent call last):
File "commcare_export/env.py", line 136, in emit_table
return …
```
=> Provide a helpful error message on "Row size too large"

README.md, examples/scheduled_run_linux.sh, examples/scheduled_run_windows.bat
This PR speaks to both the following tickets:
- [Create example scripts for executing a DET run on both Windows and Linux](https://dimagi.atlassian.net/browse/SC-3551)
- [Update DET repo README](https://dimagi.atlassian.net/browse/SC-3552)
Some example scripts have been added to the `examples/` directory which can be used by the OS's task scheduler to run the DET on a scheduled basis.
=> Add sample schedule script and update README on how to schedule runs

commcare_export/cli.py, commcare_export/commcare_hq_client.py, tests/test_cli.py, tests/test_commcare_hq_client.py
https://dimagi.atlassian.net/browse/SC-3407
Improving on some validations around expected output filename for the passed in output format.
1. Taking hints from how the [writer](https://github.com/dimagi/commcare-export/blob/a4fcf3fb19021c0a4cb33d58dd44a9df346c4d7a/commcare_export/cli.py#L339) is picked for a format, validated the extensions for csv, xls and xlsx. CSV files are actually stored in a zip file. Earlier using csv extension for csv format only gave a [warning](https://github.com/dimagi/commcare-export/blob/a4fcf3fb19021c0a4cb33d58dd44a9df346c4d7a/commcare_export/cli.py#L346-L352), we are now making it mandatory.
2. Additionally, for other non-sql output (json/markdown), validated that an extension is present in output filename, if used.
This will cause errors if users …
=> Improve DET errors
