dimagi/commcare-export

commcare_export/cli.py, commcare_export/excel_query.py, commcare_export/minilinq.py, tests/test_excel_query.py, tests/test_minilinq.py
=> allow specifying missing value replacement

README.md
=> --output docs

commcare_export/env.py, tests/test_minilinq.py
https://manage.dimagi.com/default.asp?254676
=> correctly handle unicode in map functions

commcare_export/writers.py, tests/test_writers.py
https://manage.dimagi.com/default.asp?256434
=> better support for mysql boolean

README.md, commcare_export/cli.py, commcare_export/env.py, commcare_export/map_format.py, commcare_export/minilinq.py, tests/test_map_format.py, tests/test_minilinq.py, tests/test_misc.py
https://manage.dimagi.com/default.asp?257863
buddy @proteusvacuum 
best reviewed by commit :fish:
=> allow mapping question values to attachment URL

commcare_export/cli.py, commcare_export/commcare_hq_client.py, commcare_export/writers.py
This will help to reduce duplicate work if an export get's interrupted for any reason.
=> checkpoint more frequently when exporting to SQL

commcare_export/cli.py
https://manage.dimagi.com/default.asp?260621
=> default missing-value to None for SQL

commcare_export/commcare_minilinq.py, tests/test_commcare_hq_client.py
Rather than requiring a reindex of all our form indices use a filter that works with new & old docs
=> filter forms by server_modifed_on or received_on

commcare_export/map_format.py, tests/test_map_format.py
[Ticket](https://manage.dimagi.com/default.asp?258796)
I could not run and test this because i could not finish set up but looks like the fix for this.
@snopoke do you have this running to quickly test it?
=> Update regex check to allow use of ()s within the arg

MANIFEST.in, commcare_export/checkpoint.py, commcare_export/cli.py, commcare_export/writers.py, migrations/README, migrations/manage.py, migrations/migrate.cfg, migrations/versions/001_create_table.py, migrations/versions/002_add_final.py, migrations/versions/003_rename_time_of_run_to_since_param.py, migrations/versions/004_add_back_time_of_run.py, setup.py, tests/test_writers.py
Old method was getting pretty dodge
=> use proper migrations framework

commcare_export/writers.py
https://manage.dimagi.com/default.asp?267952
=> allow changing varchar columns when in 'strict types' mode

commcare_export/cli.py, commcare_export/commcare_hq_client.py
Ticket: https://manage.dimagi.com/default.asp?273839
Enabling authentication with username, password, and apikey, which allows the tool to be used when 2 factor auth is required for users in a domain.
=> Implement api key authentication

README.md
Just reworded something that I found slightly confusing.
=> Reworded an instruction

.travis.yml, .travis/wait.sh, README.md, commcare_export/writers.py, setup.py, tests/conftest.py, tests/test_checkpointmanager.py, tests/test_writers.py
PR into https://github.com/dimagi/commcare-export/pull/75
=> testing for mssql

.travis.yml, .travis/wait.sh, README.md, commcare_export/writers.py, setup.py, tests/conftest.py, tests/test_checkpointmanager.py, tests/test_writers.py
on top of https://github.com/dimagi/commcare-export/pull/74
=> refactor tests

commcare_export/env.py, tests/test_minilinq.py
https://manage.dimagi.com/default.asp?276256
https://github.com/dimagi/commcare-export/issues/59
=> handle blank str2num

commcare_export/checkpoint.py
* files aren't places in the python env if they aren't in a package
* when installed alembic needs to be told where to find the migrations
=> fix migrations

commcare_export/cli.py, commcare_export/writers.py
Pretty sure we haven't seen this in the wild yet since it results in errors on subsequent runs when it tried to re-add the same column again.
=> check for max column lengths

commcare_export/commcare_hq_client.py
Looks like checkpointing has been broken since: https://github.com/dimagi/commcare-export/pull/83
Affects v 0.22.0
=> set checkpoint manager when cloning

README.md, commcare_export/checkpoint.py, commcare_export/cli.py, commcare_export/commcare_hq_client.py, tests/test_checkpointmanager.py, tests/test_commcare_hq_client.py
The main goal with this is to reduce the complexity of the cli code
This is a pure refactor and shouldn't change any actual functionality.
Can review per commit :blowfish:
=> refactor and simplify

commcare_export/commcare_hq_client.py, commcare_export/commcare_minilinq.py, tests/test_commcare_minilinq.py
With https://github.com/dimagi/commcare-hq/pull/21182
=> order by server_modified_on

commcare_export/cli.py, tests/test_cli.py
Adresses https://github.com/dimagi/commcare-export/issues/95
=> disable checkpointing when providing since or until params

commcare_export/cli.py, commcare_export/commcare_hq_client.py, setup.py, tests/test_commcare_hq_client.py
Addresses https://github.com/dimagi/commcare-export/issues/103 and https://github.com/dimagi/commcare-export/issues/102
=> handle server errors with backoff

commcare_export/writers.py
https://trello.com/c/v8jSgmrX/87-crs-items-for-q4-navarcharmax
🐡
=> use nvarchar(max) for mssql databases

commcare_export/writers.py
This check is better because it's backwards compatible with previous versions so it won't change a VARCHAR to a TEXT unless necessary
=> better strict type check

commcare_export/commcare_minilinq.py
This works locally. Any reason not to add it?
Also, do we know why users / apps / web users aren't documented at all?
=> support locations in DET

commcare_export/writers.py
Prevents oracle dialects from failing due to lack of constraint knowledge
=> Oracle Support

setup.py
pypi supports markdown now so this pandoc workflow is no longer necessary
=> just use markdown README

tests/test_minilinq.py
Sorry for breaking the CI tests. But thanks to you adding me to the project, I can push changes to the Dimagi repo and the integration tests pass.
=> Fix substr test and add one for non-string argument

README.md
https://docs.travis-ci.com/user/migrate/open-source-repository-migration#do-i-need-to-make-any-other-changes
=> travis-ci.{org -> com}

commcare_export/checkpoint.py, commcare_export/commcare_hq_client.py, commcare_export/excel_query.py, examples/demo-deliveries.json, examples/demo-pregnancy-cases-with-forms.json, examples/demo-pregnancy-cases.json, examples/demo-registrations.json, migrations/versions/a56c82a8d02e_add_detail_to_checkpoint.py, tests/test_checkpointmanager.py, tests/test_cli.py, tests/test_excel_query.py
This will be useful for debugging and potentially for migrations in the future.
=> add "data source" and "last_doc_id" to checkpoints

commcare_export/commcare_minilinq.py
depends on https://github.com/dimagi/commcare-hq/pull/29308
=> add ability to export messaging events

commcare_export/commcare_minilinq.py
Merge after https://github.com/dimagi/commcare-hq/pull/29869 is deployed
=> update date filtering params for messaging-event

commcare_export/commcare_minilinq.py, tests/test_commcare_hq_client.py
Merge after https://github.com/dimagi/commcare-hq/pull/29991 is live.
=> use 'date_last_activity' for filtering / ordering of messaging data

commcare_export/cli.py
Get the username and password from the user before they are used to create the API client.
=> prompt for username & password before they are needed

.travis.yml, README.md
Build was failing with error:
```
$ docker pull microsoft/mssql-server-linux:2017-latest
Error response from daemon: pull access denied for microsoft/mssql-server-linux, repository does not exist or may require 'docker login'
The command "docker pull microsoft/mssql-server-linux:2017-latest" failed and exited with 1 during .
```
=> Change location of mssql docker image

README.md, setup.py
https://github.com/dimagi/commcare-export/pull/200#pullrequestreview-802216983 
Easiest commit / commit (🐡 / 🐡)
=> Add optional dependencies

README.md, commcare_export/minilinq.py
I accidentally left these out.
=> Add missing types

README.md
Minor rewording to clarify documentation
=> Clarify that we're talking about query formats

README.md
An effort to make documentation better for users not familiar with python.
https://dimagi.atlassian.net/browse/SC-3350
=> Expands on python & virtualenv installation steps
